### PR TITLE
Correcting Transactional Session sample

### LINKED ISSUE #6239: Feedback: 'Using TransactionalSession with Entity Framework and ASP.NET Core'
Feedback for 'Using TransactionalSession with Entity Framework and ASP.NET Core' https://docs.particular.net/samples/transactional-session/aspnetcore-webapi/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/samples/transactional-session/aspnetcore-webapi/sample.md

The .NET 7 sample will always commit the transactional session, even when an exception is thrown in the controller. Unlike with middleware, the result needs to be explicitly checked when using filters. The change below should make it behave the same as the middleware based sample.

```
    public async Task OnResourceExecutionAsync(ResourceExecutingContext context, ResourceExecutionDelegate next)
    {
        if (context.ActionDescriptor.Parameters.Any(p => p.ParameterType == typeof(ITransactionalSession)))
        {
            var session = context.HttpContext.RequestServices.GetRequiredService<ITransactionalSession>();
            await session.Open(new SqlPersistenceOpenSessionOptions());

            var result = await next();

            if (result.Exception != null)
            {
                await session.Commit();
            }
        }
        else
        {
            await next();
        }
    }
```

### PR DESCRIPTION
**Pull request by awright18**
- Fixes #6239

### CODE REVIEW

**Review by danielmarbach — APPROVED** [review]

File: samples/transactional-session/aspnetcore-webapi/SqlPersistenceTS_6/WebApplication/MessageSessionFilter.cs [hunk 1]
```diff
@@ -14,9 +14,12 @@ public async Task OnResourceExecutionAsync(ResourceExecutingContext context, Res
             var session = context.HttpContext.RequestServices.GetRequiredService<ITransactionalSession>();
             await session.Open(new SqlPersistenceOpenSessionOptions());
 
-            await next();
+            var result = await next();
 
-            await session.Commit();
+            if(result.Exception == null)
```
Comment (danielmarbach) [inline samples/transactional-session/aspnetcore-webapi/SqlPersistenceTS_6/WebApplication/MessageSessionFilter.cs:19]: Don't remember what LangVersion we use these days but if you want you could the `is null` pattern.

Comment (awright18) [reply samples/transactional-session/aspnetcore-webapi/SqlPersistenceTS_6/WebApplication/MessageSessionFilter.cs:19]: good idea!
